@startuml
!theme plain
skinparam componentStyle uml2
skinparam defaultTextAlignment center

title Микросервисная архитектура BLMS

actor "Менеджер склада" as Manager
actor "Кальян-мастер" as Master
actor "Аналитик" as Analyst

cloud "Банковский эквайринг" as BankAPI

queue "Message Broker\n(Kafka)" as EventBus

package "API Gateways" {
    [Lounge Gateway] as LoungeGateway
    [Storage Gateway] as StorageGateway
    [Analytics Gateway] as AnalyticsGateway
}

package "Inventory Domain" {
    component [Inventory Service] as Inventory
    database "Inventory DB\n(PostgreSQL)" as InvDB
    note right of Inventory
        - Табак, Угли, Мундштуки
        - Напитки (кол-во)
        - Кальяны (инвентарь)
    end note
}

package "Lounge Domain" {
    component [Lounge Service] as Lounge
    database "Lounge DB\n(PostgreSQL)" as LoungeDB
    note right of Lounge
        - Бронь пространств
        - Бронь кальянов
        - Чеки (Fact of Sale)
        - Статусы оплаты
        - Расчет стоимости
        - Черный список
    end note
}

package "Loyalty Domain" {
    component [Loyalty Service] as Loyalty
    database "Loyalty DB\n(PostgreSQL)" as LoyaltyDB
    note right of Loyalty
        - Гости (Профиль)
        - Баллы лояльности
    end note
}

package "Finance Domain" {
    component [Payment Service] as Payment
}

package "Analytics Domain" {
    component [Analytics Service] as Analytics
    database "(PostgreSQL / ClickHouse)" as StatsDB
    note bottom of Analytics
        - Средний чек
        - Продажи по категориям
        - Рост пользователей
        - Возвращаемость (Retention)
    end note
}

Manager --> StorageGateway : Управление складом
Master --> LoungeGateway : Управление чеком,\nбронью, статусом мест
Analyst --> AnalyticsGateway : Аналитика

StorageGateway --> Inventory : REST/gRPC
LoungeGateway --> Lounge : REST/gRPC
LoungeGateway --> Loyalty : REST/gRPC
AnalyticsGateway --> Analytics : REST/gRPC

Lounge ..> Inventory : Проверка наличия,\nсписание при продаже
Lounge .down.> Loyalty : Списание баллов,\nначисление баллов
Lounge .down.> Payment : Инициация оплаты

Inventory -down-> InvDB
Lounge -left-> LoungeDB
Loyalty -down-> LoyaltyDB
Analytics -down-> StatsDB

Payment ..> BankAPI : Проведение транзакции

Lounge -down-> EventBus : Событие: OrderPaid\n(сумма, позиции)
Loyalty -down-> EventBus : Событие: UserRegistered,\nPointsSpent

EventBus -up-> Analytics : Потребление событий\nдля отчетов

@enduml